### PR TITLE
Updated splash page

### PR DESCRIPTION
**Pull request by garrying**
Follow up to https://github.com/hyphacoop/organizing/issues/219

This PR is a patch to get the look-and-feel of the site aligned with the deck.

### CODE REVIEW

**Review by dcwalk — APPROVED** [review]
Looks awesome! :mushroom: :muscle: 

Slight comments, not blocking: 
- the corp number footer is dark text... I think this breaks from the deck, but not sure how you are seeing this
- do we want to link to the unsplash image? (I think the sample they provide on the side does this)
- the favicon is still the same, is that intended for now?

**Review by benhylau — APPROVED** [review]
>the corp number footer is dark text...

That does look a little awkward but also think it should be subtle. Not sure of options.

@garrying thanks again for getting this done on short timeline.

**Comment by garrying** [comment]
Linked to the Unsplash in cb0ba42. Let's follow up on the other points separately.

**Comment by patcon** [comment]
Looks effin rad @garrying! Thanks a ton

> the corp number footer is dark text

i like it.

> Let's follow up on the other points separately.

:+1: Poof'd a small issue for updating favicon, if that's alright

**Pull request merged**
